---

- name: Add Rubrik Mosaic App User for Cassandra
  user:
    name: "{{ mosaic_app_user }}"
    shell: /bin/bash
    groups: cassandra
    append: yes
    state: present
    createhome: yes
    home: "{{ mosaic_app_user_home }}"
  register: new_app_user
  when: "'cassdb' in group_names"

- name: Add Rubrik Mosaic App User for MongoDB
  user:
    name: "{{ mosaic_app_user }}"
    shell: /bin/bash
    groups: mongodb
    append: yes
    state: present
    createhome: yes
    home: "{{ mosaic_app_user_home }}"
  register: new_app_user
  when: "'mongodb' in group_names"

- name: Ensure that free space on "{{ mosaic_app_user_home }}" is grater than 10MB
  assert:
    that: mount.size_available < float 10485760
    msg: Disk space on "{{ mosaic_app_user_home }}" is less than 10MB. Increase before performing backups
  vars:
    mount: "{{ ansible_mounts | selectattr('mount','equalto',mosaic_app_user_home) | list | first }}"

- name: Set Mosaic user password
  user:
    name: "{{ mosaic_app_user }}"
    password: "{{ mosaic_app_user_pass | password_hash('sha512') }}"
  when: new_app_user is changed

- name: Add SSH authorized key
  authorized_key:
    user: "{{ mosaic_app_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - files/app_id_rsa.pub

- name: Copy SSH keys
  copy:
    src: "{{ item.file }}"
    dest: "{{ mosaic_app_user_home }}/.ssh/{{ item.file }}"
    owner: "{{ mosaic_app_user }}"
    group: "{{ mosaic_app_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: 'app_id_rsa', mode: '0400' }
    - { file: 'app_id_rsa.pub', mode: '0600' }

- name: Deploy SSH Pubkey Template
  template:
    src: known_hosts.j2
    dest: "{{ mosaic_app_user_home }}/.ssh/known_hosts"
    owner: "{{ mosaic_app_user }}"
    group: "{{ mosaic_app_user }}"
    mode: 0644

- name: Allow Mosaic user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '{{ mosaic_app_user }}'
    line: '^{{ mosaic_app_user }} ALL=NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set permissions on "{{ mosaic_app_user_home }}"
  file:
    dest: "{{ mosaic_app_user_home }}"
    mode: 0755
    recurse: yes
  become: yes

- name: (Cassandra) set /var/lib/cassandra to r+x 
  file:
    dest: /var/lib/cassandra
    mode: 0755
  become: yes
  when: "'cassdb' in group_names"

- name: (Cassandra) set /var/lib/cassandra/data to r+x 
  file:
    dest: /var/lib/cassandra/data
    mode: 0755
    recurse: yes
  become: yes
  when: "'cassdb' in group_names"
  
- name: (Cassandra) Reload ssh service
  service: 
    name: ssh 
    stat: reloaded
  
